# Trigger security scans in Checkmarx

name: Security Scan

on:
  workflow_call:
    inputs:
      build_runner_label:
        description: Select the runner for those steps which do not rely on access to internal services. Value is passed to 'runs-on' config. For github-hosted use 'ubuntu-latest'
        default: ubuntu-latest
        type: string
      cx_base_uri:
        default: https://eu.ast.checkmarx.net
        type: string
      cx_tenant:
        default: unzer
        type: string
      cx_tags:
        description: List of tags associated to scans
        required: false
        type: string

    secrets:
      CX_CLIENT_ID:
        required: true
      CX_CLIENT_SECRET:
        required: true

jobs:
  scan:
    name: Checkmarx One 👮‍♀️
    runs-on:  ${{ inputs.build_runner_label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      # https://github.com/Checkmarx/ast-github-action
      # See for additional_params https://checkmarx.com/resource/documents/en/34965-68643-scan.html
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@2.0.18
        with:
          base_uri: ${{ inputs.cx_base_uri }}
          cx_tenant: ${{ inputs.cx_tenant }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --sast-filter '!tools/**/*,!docs/**/*,!**/src/test/**/*' --iac-security-filter '!tools/**/*,!docs/**/*,!**/src/test/**/*' --sca-filter '!tools/**/*,!docs/**/*,!**/src/test/**/*' --tags '${{ inputs.cx_tags }}'
