name: Validate Pull-Request

on:
  workflow_call:
    inputs:
      jira_alias:
        description: Short name of the JIRA project
        required: true
        type: string
      allow_version_bumps:
        description: Allows PRs created automatically to bump dependency versions.
        required: false
        type: boolean
        default: false

jobs:
  title:
    name: PR title is valid
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR starts with ticket or version bump indicator
        shell: bash
        run: |
          prefix="${{ inputs.jira_alias }}"
          input="${{ github.event.pull_request.title }}"
          bump_regex="^npm\(deps-dev\): bump .*|^npm\(deps\): bump .*|^Bump .*|^maven \(deps\): bump .*|^maven \(deps-dev\): bump .*"

          if [[ $input =~ .*${prefix}.* ]]
          then
          	echo "Valid"
            exit 0
          fi

          if [[ inputs.allow_version_bumps ]]
          then
          	if [[ $input =~ $bump_regex ]]
            then
              echo "Valid"
              exit 0
            fi
          fi

          echo "Not a valid value:"
          echo "${input}"
          exit 1
  
  branch:
    name: Branch has a valid name
    runs-on: ubuntu-latest

    steps:
      - name: Verify branch name
        shell: bash
        run: |
          validate_branch() {
            local branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

            local valid_names=("main", "master", "develop")
            for name in "${valid_names[@]}"; do
              if [[ $name == "$branch_name" ]]; then
                return 0
              fi
            done

            local pattern="${{ inputs.jira_alias }}-[0-9]+[/]."
            if [[ $branch_name =~ $pattern ]]; then
              return 0
            fi

            echo "Branch name $branch_name is not allowed."
            echo "Make sure, branch name follows pattern '${{ inputs.jira_alias }}-{TICKET_NUMBER}/{TICKET_TITLE}'"
            return 1
          }

          validate_branch || exit 1
          echo "Branch name is valid"
