name: Validate Pull-Request

on:
  workflow_call:
    inputs:
      jira_alias:
        description: Short name of the JIRA project
        required: true
        type: string

jobs:
  title:
    name: PR title has a ticket reference
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR starts with ticket
        shell: bash
        run: |
          prefix="${{ inputs.jira_alias }}"
          input="${{ github.event.pull_request.title }}"

          if [[ $input =~ .*${prefix}.* ]]
          then
          	echo "Valid"
          else
          	echo "Not a valid value:"
          	echo "${input}"
            exit 1
          fi
  
  branch:
    name: Branch has a valid name
    runs-on: ubuntu-latest

    steps:
      - name: Verify branch name
        shell: bash
        run: |
          validate_branch() {
            local branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

            local valid_names=("main", "master", "develop")
            for name in "${valid_names[@]}"; do
              if [[ $name == "$branch_name" ]]; then
                return 0
              fi
            done

            local pattern="${{ inputs.jira_alias }}-[0-9]+[/]."
            if [[ $branch_name =~ $pattern ]]; then
              return 0
            fi

            echo "Branch name $branch_name is not allowed."
            echo "Make sure, branch name follows pattern '${{ inputs.jira_alias }}-{TICKET_NUMBER}/{TICKET_TITLE}'"
            return 1
          }

          validate_branch || exit 1
          echo "Branch name is valid"
